name: HIL Test Pipeline
on: [push, pull_request]

jobs:

  lint-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t test-bench-ci .
      - run: docker run --rm test-bench-ci ruff check src/ tests/ # lint for python
      - name: Run cppcheck
        if: ${{ hashFiles('**/*.c', '**/*.h', '**/*.cpp', '**/*.hpp', '**/*.cc', '**/*.cxx') != '' }}
        run: docker run --rm test-bench-ci cppcheck --enable=all board/ # static analysis for c

  build-and-test:
    needs: lint-and-analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t test-bench-ci .
      - run: docker run --rm test-bench-ci pytest