name: HIL Test Pipeline
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5 # download and install python on the GitHub Actions virtual machine for CI
        with:
          python-version: '3.12' # recent and stable

      - name: Install dependencies
        run: | # puts the next line on multiple lines
          pip install mypy pytest ruff
        
      - name: Run Linter (Ruff)
        run: ruff check .

      - name: Run Type Checker (Mypy)
        run: mypy .

      - name: Run Tests (Pytest)
        run: pytest tests/